# Generated by Django 4.0.4 on 2022-05-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_studentdata_delete_studentdatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='present_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='total_days',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
